### ISSUE TITLE
gy-91 patch as a branch or a different board

### ISSUE THREAD

**Issue by awright424** [HefnySco/OBAL#31]
is it a possibility of creating a branch or different board for the gy-91 I get this error trying to apply your patch.

> alex@DESKTOP-ITUSAHU:~/ardupilot$ git apply obal_gy91.patch
error: corrupt patch at line 35

or fix the patch. I downloaded the files to the root directory of the ardupilot files and got that error when applying the patch

**Comment by HefnySco** [comment]
fixed.... thank you for highlighting this issue.
Actually I prefer to leave it as a batch because OBAL is a part if Ardupilot release, so you should always be able to use latest updates and run this patch to convert OBAL-IMU-9250 to OBAL-GY91.

**Comment by awright424** [comment]
works for me now. I am getting a config error. I bought my modules from amazon and you mentioned the led should not be red so it may be that I have a fake

<img width="489" alt="image" src="https://user-images.githubusercontent.com/2151230/219961402-8a8a4dc7-ade0-4ca9-b745-ef737f2d3492.png">

**Comment by awright424** [comment]
one of the imus i ordered was bad.
