### ISSUE TITLE
Patch gy-91

### ISSUE THREAD

**Issue by highfreq** [HefnySco/OBAL#34]
I run ./waf clean

than apply patch, than recompile.

Is it ok?

How do i know the compiled is the correct patched version?

thanks.

**Comment by highfreq** [comment]
Is it ok how i applied patch?

**Comment by HefnySco** [comment]
> I run ./waf clean
> 
> than apply patch, than recompile.
> 
> Is it ok?
> 
> How do i know the compiled is the correct patched version?
> 
> thanks.

the applied patch only changes OBAL board configuration and hardly affect any other part. so It should be working unless ardupilot applied sever changes to Linux part.
