### ISSUE TITLE
Obal and ethernet port

### ISSUE THREAD

**Issue by highfreq** [HefnySco/OBAL#37]
Is there any chance obal locks up ethernet port on a raspberry 3. Everytime i launch ardurover the raspberry gets frozen and doesn't answer to network anymore.

thanks in advance.

**Comment by HefnySco** [comment]
running RPI-Zero some times consumes CPU and slows down network response when I try to connect using ssh, although if you start Arducopter using SystemCtl it will send mavlink messages over wifi with no delay.

**Comment by highfreq** [comment]
I changed param file and everything works as expected, thank you
