### ISSUE TITLE
Baro config issue

### ISSUE THREAD

**Issue by highfreq** [HefnySco/OBAL#39]
I get this error in mission planner when connecting. I am using a GY-91 board:

 Config Error: Baro: unable to initialise driver

I applied the GY-91 patch but i got the following error:

~/ardupilot $ git apply obal_gy91.patch
error: patch failed: libraries/AP_HAL/board/linux.h:293
error: libraries/AP_HAL/board/linux.h: patch does not apply
error: patch failed: libraries/AP_HAL_Linux/SPIDevice.cpp:150
error: libraries/AP_HAL_Linux/SPIDevice.cpp: patch does not apply

**Comment by HefnySco** [comment]
I have just tested it now. I have downloaded latest version of ardupilot
```
git clone https://github.com/ArduPilot/ardupilot.git
./Tools/gittools/submodule-sync.sh 
wget https://raw.githubusercontent.com/HefnySco/OBAL/main/Software/patches/obal_gy91.patch
git apply obal_gy91.patch

```

It compiled. ... it should not give any error when applying the patch like the below.... if it does then there is something wrong with your code or you made changes already to ardupilot files so patch cannot run.
```
~/ardupilot $ git apply obal_gy91.patch
error: patch failed: libraries/AP_HAL/board/linux.h:293
error: libraries/AP_HAL/board/linux.h: patch does not apply
error: patch failed: libraries/AP_HAL_Linux/SPIDevice.cpp:150
error: libraries/AP_HAL_Linux/SPIDevice.cpp: patch does not apply
```

**Comment by highfreq** [comment]
Will retry, do i have to download dev branch?

**Comment by HefnySco** [comment]
just download the normal master or release branch of [ardupilot](https://github.com/ArduPilot/ardupilot) it works.

**Comment by highfreq** [comment]
I downloaded and applied patch, and got no error. I am now compling.

Will let you know how it goes.

**Comment by highfreq** [comment]
Same problem after compiling the patched release. At this point i guess i have a bad GY-91.

I looked round and they all look like fake, don't know where to find a true genuine GY-91.

**Comment by highfreq** [comment]
Could it be the raspberry 3 not working?
I doubt it because the battery and pwm boards are correctly picked up by the software, it is only the GY-91 not working.

**Comment by highfreq** [comment]
@HefnySco can you please elaborate a bit more on where to disable baro? I need to use OBAL on a boat so no baro needed and i get the baro init error.
where should i modify the following?

HAL_BARO_ALLOW_INIT_NO_BARO in #elif CONFIG_HAL_BOARD_SUBTYPE == HAL_BOARD_SUBTYPE_LINUX_OBAL_V1

My board is GY-91 type.

**Comment by HefnySco** [comment]
```
#elif CONFIG_HAL_BOARD_SUBTYPE == HAL_BOARD_SUBTYPE_LINUX_OBAL_V1
    
    //#define HAL_BARO_ALLOW_INIT_NO_BARO
    
    // Activate SUB Model Configuratopm
    //#define HAL_BOARD_SUBTYPE_LINUX_OBAL_V1_MPU_9250_SPI
    #define HAL_BOARD_SUBTYPE_LINUX_OBAL_V1_GY_91_SPI
    
    // Define Notify
    #define OBAL_NOTIFY_LED
    

    // GY-91 SPI Connection
    #ifdef HAL_BOARD_SUBTYPE_LINUX_OBAL_V1_MPU_9250_SPI
        #define HAL_BOARD_STORAGE_DIRECTORY "/home/pi/ardupilot"
        #define HAL_BOARD_LOG_DIRECTORY "/home/pi/ardupilot/logs"
        #define HAL_BOARD_TERRAIN_DIRECTORY "/home/pi/ardupilot/terrain"
        #define HAL_PARAM_DEFAULTS_PATH "/home/pi/ardupilot.parm"

        #define HAL_INS_PROBE_LIST PROBE_IMU_SPI(Invensense, "mpu9250", ROTATION_NONE)
        #define HAL_MAG_PROBE_LIST PROBE_MAG_IMU(AK8963, mpu9250, 0, ROTATION_NONE)
        #define HAL_BARO_PROBE_LIST PROBE_BARO_I2C(BMP085, 1, 0x77) 

        #define HAL_PROBE_EXTERNAL_I2C_COMPASSES
    #endif
    #ifdef HAL_BOARD_SUBTYPE_LINUX_OBAL_V1_GY_91_SPI
        #define HAL_BOARD_STORAGE_DIRECTORY "/home/pi/ardupilot.gy91"
        #define HAL_BOARD_LOG_DIRECTORY "/home/pi/ardupilot.gy91/logs"
        #define HAL_PARAM_DEFAULTS_PATH "/home/pi/ardupilot.parm"

        #define HAL_INS_PROBE_LIST PROBE_IMU_SPI(Invensense, "mpu9250", ROTATION_NONE)
        //#define HAL_MAG_PROBE_LIST PROBE_MAG_IMU(AK8963, mpu9250, 0, ROTATION_NONE)
        //#define HAL_BARO_PROBE_LIST PROBE_BARO_SPI(BMP280, "bmp280")
        
        #define HAL_PROBE_EXTERNAL_I2C_COMPASSES
    #endif
        #define ALLOW_ARM_NO_COMPASS
        #define HAL_DISABLE_I2C_MAGS_BY_DEFAULT
        #define HAL_BARO_ALLOW_INIT_NO_BARO
    
    #ifdef OBAL_NOTIFY_LED
        #define HAL_GPIO_A_LED_PIN        27 // You can choose between 27,22,4,12
        #define HAL_GPIO_C_LED_PIN        22 // You can choose between 27,22,4,12
        #define HAL_GPIO_B_LED_PIN        4 // You can choose between 27,22,4,12
        #define HAL_GPIO_LED_ON           1
        #define HAL_GPIO_LED_OFF          0
    #endif
    #define HAL_BUZZER_PIN                12 // You can choose between 27,22,4,12
    #define OBAL_ALLOW_ADC                1

#else
    #error "no Linux board subtype set"
#endif
```

**Comment by highfreq** [comment]
what file do i have to modify?

**Comment by HefnySco** [comment]
> what file do i have to modify?

libraries/AP_HAL/board/linux.h

**Comment by highfreq** [comment]
But if i want to use the barometer on the gy-91 what should i do to not have the barometer error?

**Comment by highfreq** [comment]
what i mean is, i think there is a barometer on the gy-91 imu, can i use it via spi? if so, how can it be used?

**Comment by highfreq** [comment]
if i uncomment the following will the baro on the gy-91 work???

//#define HAL_BARO_PROBE_LIST PROBE_BARO_SPI(BMP280, "bmp280")

**Comment by HefnySco** [comment]
I just discovered a modification in Ardupilot that corrupts OBAL
please use my version [https://github.com/HefnySco/ardupilot/tree/pr_fix_RPI_check](https://github.com/HefnySco/ardupilot/tree/pr_fix_RPI_check)  until fix is approved.

**Comment by HefnySco** [comment]
approved [https://github.com/ArduPilot/ardupilot/pull/23943](https://github.com/ArduPilot/ardupilot/pull/23943)
