### ISSUE TITLE
GY-91 board

### ISSUE THREAD

**Issue by highfreq** [HefnySco/OBAL#42]
It has become almost impossible to find a genuine GY-91 board around. I bought 4 different and all of them have different chips onboard and none of them work.
Is there a way to use a different, more available, hardware on obal?

**Comment by highfreq** [comment]
It says MP92 U601A1 2148 on the accel chip but i found other people saying it is a fake. Probably that is why accel do not work and i get INS initialization error. Now the problem is where can i find genune GY-91 boards?

**Comment by HefnySco** [comment]
IMU-9250 works well.but you need to add bmp-80 baro as I2C.

**Comment by HefnySco** [comment]
yes I bought GY-91 from AliExpress and it was fake.

**Comment by highfreq** [comment]
can i connect the 9250 on the GY-91 board?
Is 9250 same pinout as GY-91 for the GY-91 board?

**Comment by HefnySco** [comment]
Not the same pin out so you need to solder it with external wires but it will work.

**Comment by highfreq** [comment]
Do i have to change anything else in the software to make it work and to disable the barometer (i don't need barometer).

**Comment by highfreq** [comment]
Would you please tell me how to wire the 9250 on the GY-91 board.

Also, how do i calibrate accelerometer? Can i do it using Mission Planner and connect to it using ethernet or do  i have to somehow connect to the board with usb?

**Comment by HefnySco** [comment]
[image: image.png]

**Comment by HefnySco** [comment]
Yes you can calibrate using MP or QGC.

**Comment by highfreq** [comment]
Hello, the image doesn't show.

Trough QGC or MP on ethernet is ok?

**Comment by highfreq** [comment]
@HefnySco any chance you can repost the wiring pic?

**Comment by highfreq** [comment]
@HefnySco can you please repost the wiring image? It doesn't show.

I have been trying to have Obal working for more than a month now with no success.

**Comment by highfreq** [comment]
WOULD YOU MIND POSTING A WORKING PIC ON HOW TO CONNECT A 9250 TO A GY-91 BOARD?????????

**Comment by highfreq** [comment]
WOULD YOU MIND POSTING A WORKING PIC ON HOW TO CONNECT A 9250 TO A GY-91 BOARD?????????

**Comment by highfreq** [comment]
WOULD YOU MIND POSTING A WORKING PIC ON HOW TO CONNECT A 9250 TO A GY-91 BOARD?????????

**Comment by highfreq** [comment]
WOULD YOU MIND POSTING A WORKING PIC ON HOW TO CONNECT A 9250 TO A GY-91 BOARD?????????

**Comment by highfreq** [comment]
WOULD YOU MIND POSTING A WORKING PIC ON HOW TO CONNECT A 9250 TO A GY-91 BOARD?????????

**Comment by highfreq** [comment]
WOULD YOU MIND POSTING A WORKING PIC ON HOW TO CONNECT A 9250 TO A GY-91 BOARD?????????

**Comment by highfreq** [comment]
WOULD YOU MIND POSTING A WORKING PIC ON HOW TO CONNECT A 9250 TO A GY-91 BOARD?????????

**Comment by highfreq** [comment]
WOULD YOU MIND POSTING A WORKING PIC ON HOW TO CONNECT A 9250 TO A GY-91 BOARD?????????

**Comment by highfreq** [comment]
WOULD YOU MIND POSTING A WORKING PIC ON HOW TO CONNECT A 9250 TO A GY-91 BOARD?????????

**Comment by highfreq** [comment]
WOULD YOU MIND POSTING A WORKING PIC ON HOW TO CONNECT A 9250 TO A GY-91 BOARD?????????

**Comment by highfreq** [comment]
WOULD YOU MIND POSTING A WORKING PIC ON HOW TO CONNECT A 9250 TO A GY-91 BOARD?????????

**Comment by highfreq** [comment]
WOULD YOU MIND POSTING A WORKING PIC ON HOW TO CONNECT A 9250 TO A GY-91 BOARD?????????

**Comment by highfreq** [comment]
WOULD YOU MIND POSTING A WORKING PIC ON HOW TO CONNECT A 9250 TO A GY-91 BOARD?????????

**Comment by highfreq** [comment]
WOULD YOU MIND POSTING A WORKING PIC ON HOW TO CONNECT A 9250 TO A GY-91 BOARD?????????

**Comment by highfreq** [comment]
WOULD YOU MIND POSTING A WORKING PIC ON HOW TO CONNECT A 9250 TO A GY-91 BOARD?????????

**Comment by highfreq** [comment]
WOULD YOU MIND POSTING A WORKING PIC ON HOW TO CONNECT A 9250 TO A GY-91 BOARD?????????

**Comment by highfreq** [comment]
WOULD YOU MIND POSTING A WORKING PIC ON HOW TO CONNECT A 9250 TO A GY-91 BOARD?????????

**Comment by highfreq** [comment]
WOULD YOU MIND POSTING A WORKING PIC ON HOW TO CONNECT A 9250 TO A GY-91 BOARD?????????

**Comment by highfreq** [comment]
WOULD YOU MIND POSTING A WORKING PIC ON HOW TO CONNECT A 9250 TO A GY-91 BOARD?????????

**Comment by highfreq** [comment]
WOULD YOU MIND POSTING A WORKING PIC ON HOW TO CONNECT A 9250 TO A GY-91 BOARD?????????

**Comment by highfreq** [comment]
WOULD YOU MIND POSTING A WORKING PIC ON HOW TO CONNECT A 9250 TO A GY-91 BOARD?????????

**Comment by highfreq** [comment]
WOULD YOU MIND POSTING A WORKING PIC ON HOW TO CONNECT A 9250 TO A GY-91 BOARD?????????

**Comment by highfreq** [comment]
WOULD YOU MIND POSTING A WORKING PIC ON HOW TO CONNECT A 9250 TO A GY-91 BOARD?????????

**Comment by highfreq** [comment]
WOULD YOU MIND POSTING A WORKING PIC ON HOW TO CONNECT A 9250 TO A GY-91 BOARD?????????

**Comment by highfreq** [comment]
WOULD YOU MIND POSTING A WORKING PIC ON HOW TO CONNECT A 9250 TO A GY-91 BOARD?????????

**Comment by highfreq** [comment]
WOULD YOU MIND POSTING A WORKING PIC ON HOW TO CONNECT A 9250 TO A GY-91 BOARD?????????

**Comment by highfreq** [comment]
WOULD YOU MIND POSTING A WORKING PIC ON HOW TO CONNECT A 9250 TO A GY-91 BOARD?????????

**Comment by highfreq** [comment]
WOULD YOU MIND POSTING A WORKING PIC ON HOW TO CONNECT A 9250 TO A GY-91 BOARD?????????

**Comment by highfreq** [comment]
WOULD YOU MIND POSTING A WORKING PIC ON HOW TO CONNECT A 9250 TO A GY-91 BOARD?????????

**Comment by highfreq** [comment]
WOULD YOU MIND POSTING A WORKING PIC ON HOW TO CONNECT A 9250 TO A GY-91 BOARD?????????

**Comment by highfreq** [comment]
WOULD YOU MIND POSTING A WORKING PIC ON HOW TO CONNECT A 9250 TO A GY-91 BOARD?????????

**Comment by highfreq** [comment]
WOULD YOU MIND POSTING A WORKING PIC ON HOW TO CONNECT A 9250 TO A GY-91 BOARD?????????

**Comment by highfreq** [comment]
WOULD YOU MIND POSTING A WORKING PIC ON HOW TO CONNECT A 9250 TO A GY-91 BOARD?????????

**Comment by highfreq** [comment]
WOULD YOU MIND POSTING A WORKING PIC ON HOW TO CONNECT A 9250 TO A GY-91 BOARD?????????

**Comment by highfreq** [comment]
WOULD YOU MIND POSTING A WORKING PIC ON HOW TO CONNECT A 9250 TO A GY-91 BOARD?????????

**Comment by highfreq** [comment]
WOULD YOU MIND POSTING A WORKING PIC ON HOW TO CONNECT A 9250 TO A GY-91 BOARD?????????

**Comment by highfreq** [comment]
WOULD YOU MIND POSTING A WORKING PIC ON HOW TO CONNECT A 9250 TO A GY-91 BOARD?????????

**Comment by highfreq** [comment]
WOULD YOU MIND POSTING A WORKING PIC ON HOW TO CONNECT A 9250 TO A GY-91 BOARD?????????

**Comment by highfreq** [comment]
WOULD YOU MIND POSTING A WORKING PIC ON HOW TO CONNECT A 9250 TO A GY-91 BOARD?????????

**Comment by highfreq** [comment]
WOULD YOU MIND POSTING A WORKING PIC ON HOW TO CONNECT A 9250 TO A GY-91 BOARD?????????

**Comment by highfreq** [comment]
WOULD YOU MIND POSTING A WORKING PIC ON HOW TO CONNECT A 9250 TO A GY-91 BOARD?????????

**Comment by highfreq** [comment]
WOULD YOU MIND POSTING A WORKING PIC ON HOW TO CONNECT A 9250 TO A GY-91 BOARD?????????

**Comment by highfreq** [comment]
WOULD YOU MIND POSTING A WORKING PIC ON HOW TO CONNECT A 9250 TO A GY-91 BOARD?????????

**Comment by highfreq** [comment]
WOULD YOU MIND POSTING A WORKING PIC ON HOW TO CONNECT A 9250 TO A GY-91 BOARD?????????

**Comment by highfreq** [comment]
WOULD YOU MIND POSTING A WORKING PIC ON HOW TO CONNECT A 9250 TO A GY-91 BOARD?????????

**Comment by highfreq** [comment]
WOULD YOU MIND POSTING A WORKING PIC ON HOW TO CONNECT A 9250 TO A GY-91 BOARD?????????

**Comment by highfreq** [comment]
WOULD YOU MIND POSTING A WORKING PIC ON HOW TO CONNECT A 9250 TO A GY-91 BOARD?????????

**Comment by highfreq** [comment]
WOULD YOU MIND POSTING A WORKING PIC ON HOW TO CONNECT A 9250 TO A GY-91 BOARD?????????

**Comment by highfreq** [comment]
WOULD YOU MIND POSTING A WORKING PIC ON HOW TO CONNECT A 9250 TO A GY-91 BOARD?????????

**Comment by highfreq** [comment]
WOULD YOU MIND POSTING A WORKING PIC ON HOW TO CONNECT A 9250 TO A GY-91 BOARD?????????

**Comment by highfreq** [comment]
WOULD YOU MIND POSTING A WORKING PIC ON HOW TO CONNECT A 9250 TO A GY-91 BOARD?????????

**Comment by highfreq** [comment]
WOULD YOU MIND POSTING A WORKING PIC ON HOW TO CONNECT A 9250 TO A GY-91 BOARD?????????

**Comment by highfreq** [comment]
WOULD YOU MIND POSTING A WORKING PIC ON HOW TO CONNECT A 9250 TO A GY-91 BOARD?????????

**Comment by highfreq** [comment]
WOULD YOU MIND POSTING A WORKING PIC ON HOW TO CONNECT A 9250 TO A GY-91 BOARD?????????

**Comment by highfreq** [comment]
WOULD YOU MIND POSTING A WORKING PIC ON HOW TO CONNECT A 9250 TO A GY-91 BOARD?????????

**Comment by highfreq** [comment]
WOULD YOU MIND POSTING A WORKING PIC ON HOW TO CONNECT A 9250 TO A GY-91 BOARD?????????

**Comment by highfreq** [comment]
WOULD YOU MIND POSTING A WORKING PIC ON HOW TO CONNECT A 9250 TO A GY-91 BOARD?????????

**Comment by highfreq** [comment]
WOULD YOU MIND POSTING A WORKING PIC ON HOW TO CONNECT A 9250 TO A GY-91 BOARD?????????

**Comment by highfreq** [comment]
WOULD YOU MIND POSTING A WORKING PIC ON HOW TO CONNECT A 9250 TO A GY-91 BOARD?????????

**Comment by highfreq** [comment]
WOULD YOU MIND POSTING A WORKING PIC ON HOW TO CONNECT A 9250 TO A GY-91 BOARD?????????

**Comment by highfreq** [comment]
WOULD YOU MIND POSTING A WORKING PIC ON HOW TO CONNECT A 9250 TO A GY-91 BOARD?????????

**Comment by highfreq** [comment]
WOULD YOU MIND POSTING A WORKING PIC ON HOW TO CONNECT A 9250 TO A GY-91 BOARD?????????

**Comment by highfreq** [comment]
WOULD YOU MIND POSTING A WORKING PIC ON HOW TO CONNECT A 9250 TO A GY-91 BOARD?????????

**Comment by highfreq** [comment]
WOULD YOU MIND POSTING A WORKING PIC ON HOW TO CONNECT A 9250 TO A GY-91 BOARD?????????

**Comment by HefnySco** [comment]
![Screenshot from 2023-06-01 14-58-56](https://github.com/HefnySco/OBAL/assets/4184373/0748b533-f0f8-4e82-93b8-756d869116c3)

**Comment by HefnySco** [comment]
Use GY-91 pons as GUIDE to pins on the board.
Remember to compile ardupilot using IMU9250 configuration not GY-91.
Also if you are using RPI-Zero then there is a [bug](https://github.com/ArduPilot/ardupilot/pull/23943)  that we are working on.

**Comment by highfreq** [comment]
Connected like in the pic and compiled your branch for IMU9250 (standard version). Accelerometer is not picked up by ardupilot. In MP or QGC there is no acc detected.
Maybe the 9250 is faulty too.

**Comment by highfreq** [comment]
This thing that is almost impossible to find a genuine accel really puts this thing down.

**Comment by highfreq** [comment]
Is there a way to check if spi bus sees gyro?

**Comment by highfreq** [comment]
I am using it (trying) on a raspberry 3.

**Comment by highfreq** [comment]
@HefnySco any idea why i just can't get the acc/gyro to work? I connected it as you posted and compiled regular obal from the branche you posted from your repository.

Could it be raspberry 3 B the problem?

**Comment by DroneEngage** [comment]
Hi,
you have some steps you can do to validate:
1- use arduino board and I2C to get REGID of chips and make sure they are the correct types. not only working but report the correct types.
2- Compile Ardupilot-OBAL taking into consideration the ZRPI bug so please use this branch [HefnySco:pr_fix_RPI_check](https://github.com/HefnySco/ardupilot/tree/pr_fix_RPI_check)
This should work if everything is ok.

**Comment by highfreq** [comment]
That's the branch i used.
