### ISSUE TITLE
Could not find the program ['/opt/cross-pi-gcc/bin/arm-linux-gnueabihf-ar']

### ISSUE THREAD

**Issue by Anojan14** [HefnySco/OBAL#49]
Could not find the program ['/opt/cross-pi-gcc/bin/arm-linux-gnueabihf-ar']

After Running these Commands
(Compilled directly on the RPI)

git clone -b master --single-branch
https://github.com/ArduPilot/ardupilot.git --depth 1
cd ardupilot
./Tools/gittools/submodule-sync.sh
sudo apt install python-pip
python -m pip install empy
python -m pip install pexpect
python -m pip install future
make obal

./waf configure --toolchain=/opt/cross-pi-gcc/bin/arm-linux-gnueabihf --board obal

![image](https://github.com/HefnySco/OBAL/assets/68329611/e3e9e0f5-dad2-4ba3-bd24-281fbc13b017)

**Comment by HefnySco** [comment]
you need to install it from [https://sourceforge.net/projects/raspberry-pi-cross-compilers/files/Raspberry%20Pi%20GCC%20Cross-Compiler%20Toolchains/Buster/GCC%2010.2.0/Raspberry%20Pi%201%2C%20Zero/](https://sourceforge.net/projects/raspberry-pi-cross-compilers/files/Raspberry%20Pi%20GCC%20Cross-Compiler%20Toolchains/Buster/GCC%2010.2.0/Raspberry%20Pi%201%2C%20Zero/)

**Comment by HefnySco** [comment]
please check https://github.com/HefnySco/OBAL/wiki/06---Build-and-Install

**Comment by Anojan14** [comment]
Thanks for the fast reply 
Amazing Work
Will try this out now

**Comment by Anojan14** [comment]
May I ask how to install the tar file on SSH RPI4

**Comment by HefnySco** [comment]
This is beyond the scope of this thread. Please google for these linux related commands.

**Comment by Anojan14** [comment]
Alright thanks

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Anojan14** [comment]
Ive downloaded the Compiler
It still says it cant be found
![image](https://github.com/HefnySco/OBAL/assets/68329611/95d21fdb-62f4-4436-9bb1-792458239d46)
![image](https://github.com/HefnySco/OBAL/assets/68329611/5f2c644f-6e1b-4ef6-a112-d8aff8c411cc)

Downloaded from here : https://sourceforge.net/projects/raspberry-pi-cross-compilers/files/Raspberry%20Pi%20GCC%20Cross-Compiler%20Toolchains/Buster/GCC%2010.2.0/Raspberry%20Pi%201%2C%20Zero/

OS used :

![image](https://github.com/HefnySco/OBAL/assets/68329611/836a9c79-480f-4675-a832-34ee3cde3bda)


Please Help me Ive literally spent 3 days and night trying to fix this

**Comment by HefnySco** [comment]
Please /opt is a root folder not inside ardupilot
please you can consult poe.com for this linux issue.
