### ISSUE TITLE
Failed phys2virt prev_virt=0xf7f2f000 phys_page=0xc5e20000 Operation not permitted 

### ISSUE THREAD

**Issue by Anojan14** [HefnySco/OBAL#50]
![image](https://github.com/HefnySco/OBAL/assets/68329611/166594a9-49d7-4818-85aa-5497e8638396)

Any Ideas why Im getting this error
I feel like I'm using a wrong version of RPI OS
but when I install Buster it says the the python version is too old

**Comment by HefnySco** [comment]
You need to recompile Linux to allow CONFIG_STRICT_DEVMEM = ENABLED.

**Comment by HefnySco** [comment]
Compile Linux 64-bit
https://www.raspberrypi.org/documentation/computers/linux_kernel.html#configuring-the-kernel


Detailed Description
https://lemariva.com/blog/2019/09/raspberry-pi-4b-preempt-rt-kernel-419y-performance-test

**Comment by Anojan14** [comment]
Thank you 
I did try and rebuild the kernel didn't go to well
will try using your method thanks :) Will let you know how it goes

**Comment by Anojan14** [comment]
> Compile Linux 64-bit https://www.raspberrypi.org/documentation/computers/linux_kernel.html#configuring-the-kernel
> 
> Detailed Description https://lemariva.com/blog/2019/09/raspberry-pi-4b-preempt-rt-kernel-419y-performance-test


I am getting this error when running make -j4 zImage

![image](https://github.com/HefnySco/OBAL/assets/68329611/67c82c35-2f3f-4751-bd90-46518b8cdd05)

I'm using Ubuntu and a Rasberry Pi 4 model B (it's a quad Core)

![image](https://github.com/HefnySco/OBAL/assets/68329611/f0a9a923-7566-4363-a817-af37071d08bc)

I'm thinking some files got missing or corrupted so I deleted everything and started again

EDIT: Done the above^^
Output
![image](https://github.com/HefnySco/OBAL/assets/68329611/56612460-2b90-4912-a3d8-2d97179771a1)
![image](https://github.com/HefnySco/OBAL/assets/68329611/b60341d4-ff65-4dd7-b48a-db86529af604)


Do you have the pre-built kernel so I can Install the kernel on the RPI4 Please

**Comment by Anojan14** [comment]
Ive finished building there kernel using Rasbperry pi website the detailed one isn't working 
I'm compiling the files directly on the RPI4 as I don't have linux and don't want it

**Comment by Anojan14** [comment]
Can you please message me when you are online I need to ask you something online thanks

**Comment by HefnySco** [comment]
https://docs.google.com/document/d/1uomo_2-cMGGrQfBMLpcBvQ17OGtd19-J6zNGcjWSems/edit?usp=sharing

This is my own How-To document... it is not well written but you should be able to find your way through it.

**Comment by Anojan14** [comment]
> https://docs.google.com/document/d/1uomo_2-cMGGrQfBMLpcBvQ17OGtd19-J6zNGcjWSems/edit?usp=sharing
> 
> This is my own How-To document... it is not well written but you should be able to find your way through it.

Hello thank yoy for sharing this 
I've requested access to view this file could you please accept it thank you

**Comment by HefnySco** [comment]
> > https://docs.google.com/document/d/1uomo_2-cMGGrQfBMLpcBvQ17OGtd19-J6zNGcjWSems/edit?usp=sharing
> > This is my own How-To document... it is not well written but you should be able to find your way through it.
> 
> Hello thank yoy for sharing this I've requested access to view this file could you please accept it thank you

done

**Comment by okonon** [comment]
@HefnySco i requested access as well. Would you be able to grant it ? Thanks a lot. Also is it possible to get latest stm32 
board info?
