### ISSUE TITLE
bash: ./ardurover: cannot execute: required file not found

### ISSUE THREAD

**Issue by Anojan14** [HefnySco/OBAL#51]
![image](https://github.com/HefnySco/OBAL/assets/68329611/01762051-a931-4916-a6af-7e8f9c1fc79f)

I edited and installed the kernel susccefully  
Im stuck on this step

**Comment by HefnySco** [comment]
99% This is cross compile issue. You are using the wrong compiler.

**Comment by Anojan14** [comment]
Yes I realised that Im now getting the dev mem error which is good
I'm making the new kernel
