### ISSUE TITLE
Config Error: INS: unable to initialise driver

### ISSUE THREAD

**Issue by glenoman** [HefnySco/OBAL#56]
Hi, thanks for your work, I got OBAL board PCB and I am having problems. 

I couldn't make the ardupilot work.

 I get the error: "Config Error: INS: unable to initialise driver."

I have BMP280, MPU9250, ADS1115, PCA9685 
Only difference I made was to use BMP280 instead of BMP085. 

I made the modification in the ardupilot/libraries/AP_HAL/board/linux.h:323 as:

#define HAL_BARO_PROBE_LIST PROBE_BARO_I2C(BMP085, 1, 0x77)  
to 
#define HAL_BARO_PROBE_LIST PROBE_BARO_I2C(BMP280, 1, 0x77) 

compiled again and it doesn't work.

I can see all the component addresses on i2ctools, read data over I2C with python and read data from the MPU9250 with python via SPI. 

So I feel like I hit the wall, can you please help me?

**Comment by glenoman** [comment]
Sorry to bother, it was a case of knock-off MPU9250

**Comment by HefnySco** [comment]
Thanks for being interested in OBAL
