### ISSUE TITLE
Add more UARTs

### ISSUE THREAD

**Issue by jonas-koeritz** [HefnySco/OBAL#6]
ArduPilot is making heavy use of UART communication for GPS, telemetry, additional RX protocols, additional ESC protocols etc. This layout and hardware configuration provides only a single UART. Maybe some extra hardware would enable this to have more.

**Comment by HefnySco** [comment]
Thank you for the feedback.

RPI-Zero has 2 serials on via usb and the other via the GPIO14,15.

For RPI-4 you can use USB serial to connect to multiple devices via usb to serial. this is the fast solution.

Please try this HAT [https://www.waveshare.com/wiki/Serial_Expansion_HAT](https://www.waveshare.com/wiki/Serial_Expansion_HAT) for more options.
